name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow==2.4.2
    -name: Test
      run: |
        pytest .
    - name: Start Airflow
      run: |
         export AIRFLOW_HOME=~/airflow
         export AIRFLOW__CORE__LOAD_EXAMPLES='false'
         #airflow standalone &> airflow.log 2>&1 &
         #sleep 30
         airflow db init
         export AIRFLOW_HOME=~/airflow
         export AIRFLOW__CORE__LOAD_EXAMPLES='false'
         airflow webserver -D
         airflow scheduler -D
    - name: Dags
      run: |
         export AIRFLOW_HOME=~/airflow
         export AIRFLOW__CORE__LOAD_EXAMPLES='false'
         cp dags/* $AIRFLOW_HOME/dags
         cd $AIRFLOW_HOME
         ls -l
         airflow dags report -v > report.log
         cat report.log
         if grep -Fwq "ERROR" report.log
         then
            echo "Error detected!"
            exit 1
         fi
