# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Airflow Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:

    runs-on: apache/airflow:latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Check Dags
      run: |
        cp dags/*.py /opt/airflow/dags
        airflow standalone &> airflow.log 2>&1 &
        sleep 30
        airflow dags report -v > report.log
        cat report.log
        |
        if grep -Fwq "ERROR" report.log
        then
          echo "Error detected!"
          exit 1
        fi
    - name: Alguma Coisa
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ls -l
